-- ejecutar con system en xepdb1
CREATE TABLESPACE TBS_MABUPv1
DATAFILE 'C:\app\Diego\product\21c\oradata\XE\XEPDB1\tbs_mabupv1.dbf'
SIZE 100M 
AUTOEXTEND ON NEXT 10 M
MAXSIZE 200M
ONLINE;

-- SE CREA EL USUARIO
CREATE USER USR_MABUP
IDENTIFIED BY 123456789
DEFAULT TABLESPACE TBS_MABUPv1
QUOTA UNLIMITED ON TBS_MABUPv1;

-- SE CREA EL ROL
CREATE ROLE PROGRAMADOR;

-- SE ASINGNAN LOS PRIVILEGIOS AL ROL
-- si ya tienen creado este rol, omitir este paso
GRANT CREATE SESSION, CREATE TABLE, ALTER ANY TABLE, DROP ANY TABLE,
      INSERT ANY TABLE,  UPDATE ANY TABLE, DELETE ANY TABLE, CREATE ANY PROCEDURE
      TO PROGRAMADOR; 

-- SE ASIGNA EL ROL AL USUARIO (rol ue ya est� creado)
GRANT PROGRAMADOR TO USR_MABUP;

SELECT * FROM DBA_roles;
SELECT * FROM DBA_users;