-- Script para crear tablas e insertar datos en el esquema MABUP_APP
-- Conectar como: MABUP_APP / tu_contraseña_segura

-- Creación de la tabla de Usuarios
CREATE TABLE tb_Usuarios(
	id NUMBER(10, 0) NOT NULL,
	Usuario VARCHAR2(60),
	Contraseña VARCHAR2(60),
	Nombre VARCHAR2(50),
	Ap_Pat VARCHAR2(50),
	Ap_Mat VARCHAR2(50),
	Estimado_de_tiempo INTERVAL DAY(0) TO SECOND(0),
	CONSTRAINT pk_usuarios PRIMARY KEY (id)
);
/

-- Creación de la tabla de Tareas
CREATE TABLE tb_Tareas(
	id NUMBER(10, 0),
	Num_Tarea NUMBER(10, 0) GENERATED BY DEFAULT AS IDENTITY (START WITH 2005) NOT NULL,
	Titulo VARCHAR2(80),
	Fecha_Inicio DATE,
	Fecha_Entrega DATE,
	Materia VARCHAR2(50),
	Dificultad NUMBER(2, 0),
	Tema_Tarea VARCHAR2(80),
	Completado NUMBER(1) DEFAULT 0,
	CONSTRAINT pk_tareas PRIMARY KEY (Num_Tarea),
	CONSTRAINT fk_tareas_usuarios FOREIGN KEY (id) REFERENCES tb_Usuarios(id),
  CONSTRAINT chk_completado CHECK (Completado IN (0,1))
);
/


-- Insertar datos en la tabla de Usuarios
INSERT INTO tb_Usuarios (id, Usuario, Contraseña, Nombre, Ap_Pat, Ap_Mat, Estimado_de_tiempo) VALUES (1, 'Mabup', '14', '', '', '', NULL);
INSERT INTO tb_Usuarios (id, Usuario, Contraseña, Nombre, Ap_Pat, Ap_Mat, Estimado_de_tiempo) VALUES (2, 'abc@hotmai.com', '123456789', 'Emily', 'Piña', 'Sanchez', INTERVAL '02:00:00' HOUR TO SECOND);
INSERT INTO tb_Usuarios (id, Usuario, Contraseña, Nombre, Ap_Pat, Ap_Mat, Estimado_de_tiempo) VALUES (3, 'magpv@some.com', '123456789', 'Amelia Zarai', 'Sanchez', 'Gutierrez', INTERVAL '01:06:01' HOUR TO SECOND);
INSERT INTO tb_Usuarios (id, Usuario, Contraseña, Nombre, Ap_Pat, Ap_Mat, Estimado_de_tiempo) VALUES (4, 'edv@yahoo.com', '123456789', 'Diego', 'Lopez', 'Cardenaz', INTERVAL '02:00:00' HOUR TO SECOND);
INSERT INTO tb_Usuarios (id, Usuario, Contraseña, Nombre, Ap_Pat, Ap_Mat, Estimado_de_tiempo) VALUES (5, 'rock21@gmail.com', '123456789', 'maria guadalupe', 'vargas', 'najera', INTERVAL '05:10:03' HOUR TO SECOND);
/

-- Insertar datos en la tabla de Tareas
-- La columna Num_Tarea se genera automáticamente por lo que no se incluye en el INSERT
INSERT INTO tb_Tareas (id, Titulo, Fecha_Inicio, Fecha_Entrega, Materia, Dificultad, Tema_Tarea, Completado) VALUES (1, 'Resumen micro', TO_DATE('2021-02-12 11:23:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2021-02-12 10:12:00', 'YYYY-MM-DD HH24:MI:SS'), 'Microeconomia', 5, 'Costos', 0);
INSERT INTO tb_Tareas (id, Titulo, Fecha_Inicio, Fecha_Entrega, Materia, Dificultad, Tema_Tarea, Completado) VALUES (2, 'Resumen de derecho', TO_DATE('2021-01-14 17:46:40', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2021-01-19 09:11:00', 'YYYY-MM-DD HH24:MI:SS'), 'Derecho', 5, 'rdh6t', 0);
INSERT INTO tb_Tareas (id, Titulo, Fecha_Inicio, Fecha_Entrega, Materia, Dificultad, Tema_Tarea, Completado) VALUES (3, 'xdtrgxd', TO_DATE('2021-01-14 17:47:30', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2021-01-14 05:45:00', 'YYYY-MM-DD HH24:MI:SS'), 'zdfgr', 3, '6ytrdh', 0);
INSERT INTO tb_Tareas (id, Titulo, Fecha_Inicio, Fecha_Entrega, Materia, Dificultad, Tema_Tarea, Completado) VALUES (3, 'fjhxct', TO_DATE('2021-01-14 17:47:45', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2021-01-14 06:45:00', 'YYYY-MM-DD HH24:MI:SS'), 'dxg', 4, 'dxrgxdrg', 1);
INSERT INTO tb_Tareas (id, Titulo, Fecha_Inicio, Fecha_Entrega, Materia, Dificultad, Tema_Tarea, Completado) VALUES (2, 'Ejercicios de Integrales', TO_DATE('2021-01-14 19:44:59', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2021-01-22 13:54:00', 'YYYY-MM-DD HH24:MI:SS'), 'Matematicas', 9, 'cfth', 0);
INSERT INTO tb_Tareas (id, Titulo, Fecha_Inicio, Fecha_Entrega, Materia, Dificultad, Tema_Tarea, Completado) VALUES (2, 'Resumen De POO', TO_DATE('2021-01-14 21:06:17', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2021-01-15 08:16:00', 'YYYY-MM-DD HH24:MI:SS'), 'Poo', 6, 'siefudhrt', 0);
INSERT INTO tb_Tareas (id, Titulo, Fecha_Inicio, Fecha_Entrega, Materia, Dificultad, Tema_Tarea, Completado) VALUES (2, 'Cuadro foda', TO_DATE('2021-01-14 21:12:51', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2021-01-20 12:21:00', 'YYYY-MM-DD HH24:MI:SS'), 'Orientacion', 3, 'cfhtcfh', 0);
INSERT INTO tb_Tareas (id, Titulo, Fecha_Inicio, Fecha_Entrega, Materia, Dificultad, Tema_Tarea, Completado) VALUES (4, 'res', TO_DATE('2021-01-15 01:31:26', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2021-01-15 11:14:00', 'YYYY-MM-DD HH24:MI:SS'), 'Microeconomia', 5, 'yjc', 1);
INSERT INTO tb_Tareas (id, Titulo, Fecha_Inicio, Fecha_Entrega, Materia, Dificultad, Tema_Tarea, Completado) VALUES (5, 'Resumen de fisica', TO_DATE('2021-01-15 07:59:07', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2021-01-20 10:03:00', 'YYYY-MM-DD HH24:MI:SS'), 'Fisica', 7, 'MRU', 1);
INSERT INTO tb_Tareas (id, Titulo, Fecha_Inicio, Fecha_Entrega, Materia, Dificultad, Tema_Tarea, Completado) VALUES (2, 'dibujo', TO_DATE('2021-01-15 21:48:28', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2021-01-20 11:11:00', 'YYYY-MM-DD HH24:MI:SS'), 'Biologia', 3, 'dibujo industrial', 1);
INSERT INTO tb_Tareas (id, Titulo, Fecha_Inicio, Fecha_Entrega, Materia, Dificultad, Tema_Tarea, Completado) VALUES (4, 'crisis economica en pandemia', TO_DATE('2021-01-15 22:40:19', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2021-01-28 15:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Microeconomia', 8, 'desempleo y crisis economica en la actualidad', 1);
INSERT INTO tb_Tareas (id, Titulo, Fecha_Inicio, Fecha_Entrega, Materia, Dificultad, Tema_Tarea, Completado) VALUES (2, 'Graficas de punto de equilibrio', TO_DATE('2021-01-15 02:09:43', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2021-01-27 12:03:00', 'YYYY-MM-DD HH24:MI:SS'), 'Microeconomia', 4, 'sdfsdf', 0);
INSERT INTO tb_Tareas (id, Titulo, Fecha_Inicio, Fecha_Entrega, Materia, Dificultad, Tema_Tarea, Completado) VALUES (5, 'thfxcfht', TO_DATE('2021-01-15 02:16:58', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2021-01-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Derecho', 3, 'fcthhtf', 0);
/

-- Confirmar todos los cambios en la base de datos
COMMIT;
/

SELECT TABLE_NAME
FROM USER_TABLES;

SELECT * FROM TB_USUARIOS;